/*******************************************************************************
 * @file    RPC_BTL_cmn.cs
 * @brief   Auto generated by mbrpcgen.rb
 *******************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Net;
using System.Net.Sockets;
using System.Runtime.InteropServices;
namespace BTL {
    public enum Battle {
        BATTLE_ROOM_MAX = 100,
    }
	// enum helper class 
	public class HelperBattle
	{
		// convert id to string 
		static public string BattleToString( Battle v ){
			switch(v){
			case Battle.BATTLE_ROOM_MAX : return "BATTLE_ROOM_MAX";
			}
			return "unknown";
		}
		// get from stream 
		static public UInt32 get( mln.EndianStream rEs, out Battle rOut ){
			UInt32 ret=0;
			rEs.get( out ret );
			rOut = (Battle)ret;
			return 4;
		}
		// set in stream 
		static public UInt32 set( mln.EndianStream rEs, Battle rIn ){
			rEs.put((UInt32)rIn);
			return 4;
		}
	}
    public enum BattleStatus {
        BATTLESTATUS_ENTERABLE = 0,
        BATTLESTATUS_BATTLING = 1,
        BATTLESTATUS_WAITING = 2,
        BATTLESTATUS_RESERVED = 3,
    }
	// enum helper class 
	public class HelperBattleStatus
	{
		// convert id to string 
		static public string BattleStatusToString( BattleStatus v ){
			switch(v){
			case BattleStatus.BATTLESTATUS_ENTERABLE : return "BATTLESTATUS_ENTERABLE";
			case BattleStatus.BATTLESTATUS_BATTLING : return "BATTLESTATUS_BATTLING";
			case BattleStatus.BATTLESTATUS_WAITING : return "BATTLESTATUS_WAITING";
			case BattleStatus.BATTLESTATUS_RESERVED : return "BATTLESTATUS_RESERVED";
			}
			return "unknown";
		}
		// get from stream 
		static public UInt32 get( mln.EndianStream rEs, out BattleStatus rOut ){
			UInt32 ret=0;
			rEs.get( out ret );
			rOut = (BattleStatus)ret;
			return 4;
		}
		// set in stream 
		static public UInt32 set( mln.EndianStream rEs, BattleStatus rIn ){
			rEs.put((UInt32)rIn);
			return 4;
		}
	}
    public enum BattleResult {
        BATTLERESULT_SUCCESS = 0,
        BATTLERESULT_FAILURE = -1,
        BATTLERESULT_FAILURE_BATTLING = -2,
        BATTLERESULT_FAILURE_MAX_OVER = -3,
        BATTLERESULT_FAILURE_NOT_FOUND = -4,
    }
	// enum helper class 
	public class HelperBattleResult
	{
		// convert id to string 
		static public string BattleResultToString( BattleResult v ){
			switch(v){
			case BattleResult.BATTLERESULT_SUCCESS : return "BATTLERESULT_SUCCESS";
			case BattleResult.BATTLERESULT_FAILURE : return "BATTLERESULT_FAILURE";
			case BattleResult.BATTLERESULT_FAILURE_BATTLING : return "BATTLERESULT_FAILURE_BATTLING";
			case BattleResult.BATTLERESULT_FAILURE_MAX_OVER : return "BATTLERESULT_FAILURE_MAX_OVER";
			case BattleResult.BATTLERESULT_FAILURE_NOT_FOUND : return "BATTLERESULT_FAILURE_NOT_FOUND";
			}
			return "unknown";
		}
		// get from stream 
		static public UInt32 get( mln.EndianStream rEs, out BattleResult rOut ){
			UInt32 ret=0;
			rEs.get( out ret );
			rOut = (BattleResult)ret;
			return 4;
		}
		// set in stream 
		static public UInt32 set( mln.EndianStream rEs, BattleResult rIn ){
			rEs.put((UInt32)rIn);
			return 4;
		}
	}
    public enum MatchingStatus {
        MATCHINGSTATUS_MATCHING_WAIT = 0,
        MATCHINGSTATUS_MATCHING_SUCCESS = 1,
        MATCHINGSTATUS_MATCHING_FAILURE = 2,
        MATCHINGSTATUS_BATTLE_APPOINTMENT_SUCCESS = 3,
        MATCHINGSTATUS_BATTLE_APPOINTMENT_FAILURE = 4,
    }
	// enum helper class 
	public class HelperMatchingStatus
	{
		// convert id to string 
		static public string MatchingStatusToString( MatchingStatus v ){
			switch(v){
			case MatchingStatus.MATCHINGSTATUS_MATCHING_WAIT : return "MATCHINGSTATUS_MATCHING_WAIT";
			case MatchingStatus.MATCHINGSTATUS_MATCHING_SUCCESS : return "MATCHINGSTATUS_MATCHING_SUCCESS";
			case MatchingStatus.MATCHINGSTATUS_MATCHING_FAILURE : return "MATCHINGSTATUS_MATCHING_FAILURE";
			case MatchingStatus.MATCHINGSTATUS_BATTLE_APPOINTMENT_SUCCESS : return "MATCHINGSTATUS_BATTLE_APPOINTMENT_SUCCESS";
			case MatchingStatus.MATCHINGSTATUS_BATTLE_APPOINTMENT_FAILURE : return "MATCHINGSTATUS_BATTLE_APPOINTMENT_FAILURE";
			}
			return "unknown";
		}
		// get from stream 
		static public UInt32 get( mln.EndianStream rEs, out MatchingStatus rOut ){
			UInt32 ret=0;
			rEs.get( out ret );
			rOut = (MatchingStatus)ret;
			return 4;
		}
		// set in stream 
		static public UInt32 set( mln.EndianStream rEs, MatchingStatus rIn ){
			rEs.put((UInt32)rIn);
			return 4;
		}
	}
    public enum AppointmentResult {
        APPOINTMENTRESULT_SUCCESS = 0,
        APPOINTMENTRESULT_FAILURE = -1,
        APPOINTMENTRESULT_FAILURE_EMPTY_NOT_FOUND = -2,
    }
	// enum helper class 
	public class HelperAppointmentResult
	{
		// convert id to string 
		static public string AppointmentResultToString( AppointmentResult v ){
			switch(v){
			case AppointmentResult.APPOINTMENTRESULT_SUCCESS : return "APPOINTMENTRESULT_SUCCESS";
			case AppointmentResult.APPOINTMENTRESULT_FAILURE : return "APPOINTMENTRESULT_FAILURE";
			case AppointmentResult.APPOINTMENTRESULT_FAILURE_EMPTY_NOT_FOUND : return "APPOINTMENTRESULT_FAILURE_EMPTY_NOT_FOUND";
			}
			return "unknown";
		}
		// get from stream 
		static public UInt32 get( mln.EndianStream rEs, out AppointmentResult rOut ){
			UInt32 ret=0;
			rEs.get( out ret );
			rOut = (AppointmentResult)ret;
			return 4;
		}
		// set in stream 
		static public UInt32 set( mln.EndianStream rEs, AppointmentResult rIn ){
			rEs.put((UInt32)rIn);
			return 4;
		}
	}
    public class BattlePuInfo
    {
        public string ip_addr;
		public UInt32 ip_addr_strlen;
        public UInt16 port;
        public UInt64 room_hub_pu_uid;
        public UInt64 battle_pu_uid;
        public BattlePuInfo(){// default constructor 
			ip_addr = System.String.Empty;
		}
        public BattlePuInfo( string  _ip_addr, UInt32 _ip_addr_strlen, UInt16 _port, UInt64 _room_hub_pu_uid, UInt64 _battle_pu_uid ){// argument constructor 
			this.ip_addr_strlen = _ip_addr_strlen;
			this.ip_addr = _ip_addr;
            this.port = _port;
            this.room_hub_pu_uid = _room_hub_pu_uid;
            this.battle_pu_uid = _battle_pu_uid;
        }
        public BattlePuInfo(BattlePuInfo rRef){// copy constructor 
			this.ip_addr_strlen = rRef.ip_addr_strlen;
            this.ip_addr = rRef.ip_addr;
            this.port = rRef.port;
            this.room_hub_pu_uid = rRef.room_hub_pu_uid;
            this.battle_pu_uid = rRef.battle_pu_uid;
		}
		public static UInt32 length( BattlePuInfo _rChk )
		{
			UInt32 totalSize = 0;
			// STRING TYPE 
			totalSize += _rChk.ip_addr_strlen+4;
			// BASIC TYPE 
			totalSize += (2);
			// BASIC TYPE 
			totalSize += (8);
			// BASIC TYPE 
			totalSize += (8);
			return totalSize;
		}
		public static UInt32 get( mln.EndianStream rEs, BattlePuInfo _rOut )
		{
			UInt32 ofs = 0;
		// STRING TYPE 
			ofs += mln.cRPC_ID.GetStringFromStream( out _rOut.ip_addr, rEs, out _rOut.ip_addr_strlen );
		// BASIC TYPE
			rEs.get( out _rOut.port );
			ofs += 2;
		// BASIC TYPE
			rEs.get( out _rOut.room_hub_pu_uid );
			ofs += 8;
		// BASIC TYPE
			rEs.get( out _rOut.battle_pu_uid );
			ofs += 8;
			return ofs;
		}
		public static UInt32 set( mln.EndianStream rEs, BattlePuInfo _rIn )
		{
			UInt32 ofs = 0;
		// STRING TYPE
			ofs += mln.cRPC_ID.SetStringToStream( _rIn.ip_addr, rEs, _rIn.ip_addr_strlen );
		// BASIC TYPE
			rEs.put(_rIn.port);
			ofs += 2;
		// BASIC TYPE
			rEs.put(_rIn.room_hub_pu_uid);
			ofs += 8;
		// BASIC TYPE
			rEs.put(_rIn.battle_pu_uid);
			ofs += 8;
			return ofs;
		}
	} // end of class BattlePuInfo 
    public class BattleStatusInfo
    {
        public Byte entered_num;
        public Byte max_enter_num;
        public Byte status;
        public BattleStatusInfo(){// default constructor 
		}
        public BattleStatusInfo( Byte _entered_num, Byte _max_enter_num, Byte _status ){// argument constructor 
            this.entered_num = _entered_num;
            this.max_enter_num = _max_enter_num;
            this.status = _status;
        }
        public BattleStatusInfo(BattleStatusInfo rRef){// copy constructor 
            this.entered_num = rRef.entered_num;
            this.max_enter_num = rRef.max_enter_num;
            this.status = rRef.status;
		}
		public static UInt32 length( BattleStatusInfo _rChk )
		{
			UInt32 totalSize = 0;
			// BASIC TYPE 
			totalSize += (1);
			// BASIC TYPE 
			totalSize += (1);
			// BASIC TYPE 
			totalSize += (1);
			return totalSize;
		}
		public static UInt32 get( mln.EndianStream rEs, BattleStatusInfo _rOut )
		{
			UInt32 ofs = 0;
		// BASIC TYPE
			rEs.get( out _rOut.entered_num );
			ofs += 1;
		// BASIC TYPE
			rEs.get( out _rOut.max_enter_num );
			ofs += 1;
		// BASIC TYPE
			rEs.get( out _rOut.status );
			ofs += 1;
			return ofs;
		}
		public static UInt32 set( mln.EndianStream rEs, BattleStatusInfo _rIn )
		{
			UInt32 ofs = 0;
		// BASIC TYPE
			rEs.put(_rIn.entered_num);
			ofs += 1;
		// BASIC TYPE
			rEs.put(_rIn.max_enter_num);
			ofs += 1;
		// BASIC TYPE
			rEs.put(_rIn.status);
			ofs += 1;
			return ofs;
		}
	} // end of class BattleStatusInfo 
    public class BattleRoomInfo
    {
        public BattlePuInfo pu_info;
        public BattleStatusInfo status_info;
        public BattleRoomInfo(){// default constructor 
			pu_info = new BattlePuInfo();
			status_info = new BattleStatusInfo();
		}
        public BattleRoomInfo( BattlePuInfo _pu_info, BattleStatusInfo _status_info ){// argument constructor 
            this.pu_info = _pu_info;
            this.status_info = _status_info;
        }
        public BattleRoomInfo(BattleRoomInfo rRef){// copy constructor 
			this.pu_info = new BattlePuInfo(rRef.pu_info);
			this.status_info = new BattleStatusInfo(rRef.status_info);
		}
		public static UInt32 length( BattleRoomInfo _rChk )
		{
			UInt32 totalSize = 0;
			// STRUCT TYPE 
			totalSize += BattlePuInfo.length( _rChk.pu_info );
			// STRUCT TYPE 
			totalSize += BattleStatusInfo.length( _rChk.status_info );
			return totalSize;
		}
		public static UInt32 get( mln.EndianStream rEs, BattleRoomInfo _rOut )
		{
			UInt32 ofs = 0;
		// STRUCT TYPE 
			ofs += BattlePuInfo.get( rEs, _rOut.pu_info );
		// STRUCT TYPE 
			ofs += BattleStatusInfo.get( rEs, _rOut.status_info );
			return ofs;
		}
		public static UInt32 set( mln.EndianStream rEs, BattleRoomInfo _rIn )
		{
			UInt32 ofs = 0;
		// STRUCT TYPE
			ofs += BattlePuInfo.set( rEs, _rIn.pu_info );
		// STRUCT TYPE
			ofs += BattleStatusInfo.set( rEs, _rIn.status_info );
			return ofs;
		}
	} // end of class BattleRoomInfo 
    /**
     * @brief Interface ID
     */
    public enum INTFID {
        INTFID_DUMMY = 0,
        BATTLEPULIST = 1,
        ROOMHUB = 2,
        BATTLE = 3,
        MATCHING = 4,
        INTFID_MAX = 5
    };
} // namespace
